config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]

  get 'javascript-items', to: 'portfolios#javascript'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-us', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
enum status: {draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
validates_presence_of :title, :body

belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
  reject_if: lambda {|attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.javascript
    where(subtitle: 'JavaScript')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')

  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates_presence_of :name

def first_name
  self.name.split.first
end

def last_name
  self.name.split.last
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @page_title = "Our Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post was successfully destroyed.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern


  def current_user
    super || guest_user
  end

  def guest_user
    OpenStruct.new(
      name: "Guest User",
      first_name: "Guest",
      last_name: "User",
      email: "guest@example.com"
    )
  end

end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
  extend ActiveSupport::Concern

  included do
    before_action :set_page_defaults
  end

  def set_page_defaults
    @page_title = "SimplyPortfolio"
    @seo_keywords = "SimplyCoders portfolio rails fullstack"
  end

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
      before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
layout "portfolio"

  def index
    @portfolio_items = Portfolio.all
    @page_title = "Our Portfolio"
  end

  def javascript
    @javascript_portfolio_items = Portfolio.javascript
  end

  def new
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Your portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
    @page_title = @portfolio_item.title
  end

  def destroy
    #Perform the lookup
    @portfolio_item = Portfolio.find(params[:id])

    #Delete/destroy the record
    @portfolio_item.destroy

    #Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(
      :title,
      :subtitle,
      :body,
      technologies_attributes: [:name]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_helper style = ''
     if current_user.is_a?(User)
      link_to "Logout", destroy_user_session_path, method: :delete, class: style
     else
      (link_to "Register", new_user_registration_path, class: style) +
      " ".html_safe +
      (link_to "Login", new_user_session_path, class: style)
     end
  end

  def source_helper(layout_name)
    if session[:source]
      greeting = "Thanks for visiting us from #{session[:source]} and you are on the #{layout_name} layout"
      content_tag(:p, greeting, class: "source-greeting" )
    end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<tr>
  <td><%= blog.title.upcase %></td>
  <td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %>  ago</td>
  <td><%= blog.body %></td>
  <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
  <td><%= link_to 'Show', blog %></td>
  <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
  <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Blog Title</th>
      <th>Date</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

      <%= render "shared/application_nav"%>

      <%= yield %>

      <%= render "shared/application_footer"%>

      <%= source_helper("application") %>

    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>

    <%= render "shared/nav", location: 'bottom' %>

    <%= source_helper("blog") %>

  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location: 'top'  %>

    <%= login_helper %>

    <%= yield %>

    <%= source_helper("application") %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

<h1>About Us</h1>
<p>Gathered from different towns all over the world with the will to level up their professional skills, the Simply Coders started to learn code together three months ago.</p>
<p>During this amazing experience, we have confronted ourselves to many challenges and shared them as a group. This opportunity decided to converge our propectives to offer a new breath to web development, as your professional team.</p>

</div>

app/views/pages/contact.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

<h1>Work with us</h1>
<hr>
<p><%= number_to_phone " 42 42 42 42 42" %></p>

<p><%= " Email : contact@simplycoders.com " %></p>

<p><%= " Office Adress : 5 rue Thomas Mann 75013 PARIS " %></p>


<p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2626.468881550439!2d2.3793984154716505!3d48.830194410645866!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6723c04b7a7f7%3A0x1dc255898c34cdef!2sBiblioth%C3%A8que+des+Grands+Moulins!5e0!3m2!1sfr!2sfr!4v1523241983721" width="350" height="200" frameborder="0" style="border:0" allowfullscreen></p>

</div>

app/views/pages/home.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

<main role="main" class="inner cover">
  <h1 class="cover-heading">Welcome to our page</h1>
  <p class="lead">Try your awesome experience of code with Simply Coders.</p>
  <p class="lead">
    <%= link_to "About Us", about_us_path, class: "btn btn-lg btn-secondary" %>
  </p>
</main>

</div>

app/views/portfolios/_form.html.erb
  <%= form_for(@portfolio_item) do |f| %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle %>
    </div>

    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <ul>
      <%= f.fields_for :technologies do |technology_form| %>
        <li>
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name %>
        </li>
      <% end %>
    </ul>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/portfolios/_portfolio_item.html.erb
<p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p>

<p> <%= portfolio_item.subtitle %> </p>

<p> <%= portfolio_item.body %> </p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
<%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= render 'form' portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/javascript.html.erb
<h1>JavaScriptPortfolio items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<% @javascript_portfolio_items.each do |portfolio_item| %>
<p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p>
<p> <%= portfolio_item.subtitle %> </p>
<p> <%= portfolio_item.body %> </p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
<%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= render 'form' portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1> <%= @portfolio_item.title %> </h1>

<em> <%= @portfolio_item.subtitle %> </em>

<p> <%= @portfolio_item.body %> </p>

<h2>Technologies used : </h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>

app/views/shared/_application_footer.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> <b>Simply Coders</b> | © 2018 </p>
    </div>
  </footer>

</div>

app/views/shared/_application_nav.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Simply Coders &nbsp &nbsp &nbsp &nbsp &nbsp</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Us", about_us_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
    </nav>
  </div>
</header>

</div>

app/views/shared/_application_nav.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Simply Coders </h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Us", about_us_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Us", about_us_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>